### PR TITLE
Decouple codegen from current directory structure

### PR DESCRIPTION
**Pull request by zachguo**
`codegen` was tied with existing directory structure, making it hard to achieve #395 .

This PR 
- makes `codegen` a self-contained module, use relative import, fix circular import
- parameterizes `src_dir` instead of hardcoding `"source"`
- parameterizes `root_dir` instead of importing `root_dir` from project root folder (`os.getcwd()` as default)
- pre-commit hook only run `codegen` when changes are `meaningful` (ignore changed EOL whitespaces due to switching between Windows and Linux)

Existing hook and results shouldn't be changed at all, and can be tested out by running `python -m codegen`.

### CODE REVIEW

**Comment by zachguo** [comment]
And should this line import from `generated` instead?
https://github.com/OpenNaja/cobra-tools/blob/349e7a0b105827d0b9594d9a13fd032f7d51026e/source/formats/ms2/compounds/ChunkedMesh.py#L14-L15

**Comment by HENDRIX-ZT2** [comment]
> And should this line import from `generated` instead?
> https://github.com/OpenNaja/cobra-tools/blob/349e7a0b105827d0b9594d9a13fd032f7d51026e/source/formats/ms2/compounds/ChunkedMesh.py#L14-L15
> 
> (And there's one line `from generated.formats.ms2.compounds.packing_utils import *` above it.)

Yeah, there should be no imports of source.

**Comment by zachguo** [comment]
Okay, I'll handle it after the change of directory structure is done. Probably there should be a hook to ensure scenario like this, like `bin/check_imports.py`.

**Comment by ilodev** [comment]
I'm not sure, but I think games widget is used on other tools not just ovl_tool_gui (e.g. fgm_editor_gui)?

**Comment by HENDRIX-ZT2** [comment]
> I'm not sure, but I think games widget is used on other tools not just ovl_tool_gui (e.g. fgm_editor_gui)?

Nope, it's currently only used in loc tool besides ovl gui, which isn't even functional.

**Review by HENDRIX-ZT2 — APPROVED** [review]
Looks good to me!

**Pull request merged**
