### PR TITLE
Adds in customizable color changing of the theme

### PR DESCRIPTION
**Pull request by ViraLCyclopes**
Adds in several options in the preferences tab under the ovl tool UI that allows one to globally edit the theme colors for 'dark' mode.

### CODE REVIEW

**Comment by HENDRIX-ZT2** [comment]
Too hard coded to include imo

**Comment by ilodev** [comment]
As a learning exercise Viral, you might want to try and store the color values in the current config file first instead of creating a new config file. That will give you a better understanding of the current code.

**Comment by ViraLCyclopes** [comment]
i c ill give that a go

**Comment by HENDRIX-ZT2** [comment]
Still nope, don't read / write the json to alter it, change the dict.

**Comment by ViraLCyclopes** [comment]
ahh alr I think I get it now.

**Comment by ViraLCyclopes** [comment]
Gonna close this pull request for now will come back to this eventually tho in like couple weeks time gotta finish up some actual modding stuff first.

**Pull request closed without merging**
